# Generated by Django 5.1.6 on 2025-03-01 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.aula')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.material'),
        ),
        migrations.CreateModel(
            name='Participant_Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oracao', models.BooleanField(default=False)),
                ('leitura', models.BooleanField(default=False)),
                ('licao', models.BooleanField(default=False)),
                ('culto', models.BooleanField(default=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.attendance')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth', models.DateField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.gender')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.person'),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.role'),
        ),
        migrations.AddField(
            model_name='participant',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.turma'),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_ebd_app.turma'),
        ),
    ]
