# Generated by Django 5.1.6 on 2025-03-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_ebd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
